### ISSUE TITLE
Expose Commerce constructor, or arguments for it somehow

### ISSUE THREAD

**Issue by robbieaverill** [chec/commercerays-plugin#1]
This plugin repo abstracts the Commerce.js constructor away, so any consumers will not have access to it. Our themes will need to be able to control the `options` object in order to set a custom `X-Chec-Agent` header for channel tracking in the API, which is currently not possible.

**Comment by ScopeyNZ** [comment]
Yeah we can add an argument to the `withCommerceRays` HOC for Commerce.js options
